AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  ApproverMailAddress:
    Type: String

  SupportMailAddress:
    Type: String

  LambdaAccountCreationRole:
    Type: String

  OrgRootID:
    Type: String

  OrgUnitID:
    Type: String

Resources:

#Lambda Create
  LambdaAccountCreationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.8
      CodeUri: 's3://accountcreationXXXXXXXXXXXX/code/account/LambdaAccountCreationFunction.zip'
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: !Ref LambdaAccountCreationRole
      Environment:
        Variables:
          approver_mail_address: !Sub '${ApproverMailAddress}'
          support_mail_address: !Sub '${SupportMailAddress}'
          customer_manual_url: >-
            https://ashisuto-aws-manual.s3.ap-northeast-1.amazonaws.com/aws_account_guide.pdf
          org_root_id: !Sub '${OrgRootID}'
          org_unit_id: !Sub '${OrgUnitID}'
          spreadsheet_url: >-
            https://docs.google.com/spreadsheets/d/1wMhuPQmBR1ES6yhxdqyhX6FH0z5UR1-ql5SwZ1O4o7k/edit#gid=1485126580

Outputs:
  LambdaAccountCreation:
    Value: !GetAtt LambdaAccountCreationFunction.Arn
    Export:
      Name: LambdaAccountCreation