AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  Areyougoingtodeploytotestingsite:
    Type: String

  LambdaSendEmailRole:
    Type: String

  SupportMailAddress:
    Type: String

  ApproverMailAddress:
    Type: String

Conditions:
  DEBUG: !Equals [!Ref Areyougoingtodeploytotestingsite, true]

Resources:

#Lambda Create  
  LambdaHumanApprovalSendEmailFunctbPOXgamoTfIF:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.lambda_handler
      Runtime: nodejs14.x
      CodeUri: 's3://accountcreationXXXXXXXXXXXX/code/send/LambdaHumanApprovalSendEmailFunction.zip'
      Description: ''
      MemorySize: 128
      Timeout: 25
      Role: !Ref LambdaSendEmailRole
      Environment:
        Variables:
          support_mail_address: !Sub '${SupportMailAddress}' 
          approver_mail_address: !Sub '${ApproverMailAddress}'
          DEBUG_MODE: !Sub '${Areyougoingtodeploytotestingsite}'
          customer_manual_url: >-
            https://ashisuto-aws-manual.s3.ap-northeast-1.amazonaws.com/aws_account_guide.pdf
          spreadsheet_url: >-
            https://docs.google.com/spreadsheets/d/1wMhuPQmBR1ES6yhxdqyhX6FH0z5UR1-ql5SwZ1O4o7k/edit#gid=1485126580
          mailsubject_prefix: !If
            - DEBUG
            - '【AWS再販テスト】'
            - '【AWS再販】'

Outputs:
  LambdaSendEmail:
    Value: !GetAtt LambdaHumanApprovalSendEmailFunctbPOXgamoTfIF.Arn
    Export:
      Name: LambdaHumanApprovalSendEmailFunctbPOXgamoTfIF