AWSTemplateFormatVersion: 2010-09-09
Description: SES Create

Parameters:
  EmailDomain:
    Type: String

Resources:

#SES Create
  SES:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Sub '${EmailDomain}'

Outputs:
  SES:
    Value: !Ref SES
    Export:
      Name: SES